# Generated by Django 4.2.7 on 2023-11-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menutable_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='no_of_guest',
            field=models.IntegerField(),
        ),
    ]
