# Generated by Django 4.2.7 on 2023-11-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_delete_bookingtable_alter_menutable_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('no_of_guest', models.IntegerField(max_length=6)),
                ('booking_date', models.DateTimeField()),
            ],
        ),
    ]
