# Generated by Django 4.2.7 on 2023-11-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_bookingtable_no_of_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='booking_date',
            field=models.DateTimeField(default=True),
        ),
    ]
