# Generated by Django 4.2.7 on 2023-11-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_guest',
            field=models.IntegerField(default=6),
        ),
    ]
