# Generated by Django 4.2.7 on 2023-11-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_delete_bookingtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('no_of_guest', models.IntegerField()),
                ('booking_date', models.DateTimeField()),
            ],
        ),
    ]
