# Generated by Django 4.2.7 on 2023-11-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_bookingtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='booking_date',
            field=models.DateTimeField(default=5),
        ),
    ]
